spring:
  datasource:
    url: jdbc:mysql://localhost:3306/missyou?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: wyj931109

  jpa:
    show-sql: true

  redis:
    localhost: localhost
    port: 6379
    database: 7
    password:
    listen-pattern: __keyevent@7__:expired

missyou:
  security:
    jwt-key: wangyijie111
    token-expired-in: 86400000
  order:
    max-sku-limit: 777
    pay-time-limit: 3600
    pay-callback-host: http://4vdee7.natappfree.cc
    pay-callback-path: /v1/payment/wx/notify