spring:
  datasource:
    url: jdbc:mysql://localhost:3306/missyou?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: wyj931109

  jpa:
    show-sql: true

missyou:
  security:
    jwt-key: wangyijie111
    token-expired-in: 86400000
  order:
    max-sku-limit: 777
    pay-time-limit: 3600
    pay-callback-host: http://wangyijie11.natapp1.cc
    pay-callback-path: /v1/payment/wx/notify